#!/usr/bin/perl


$encrypted_text = "text generated by the encrypt_rail_fence.pl script";
$len_text = length($encrypted_text);


if($len_text % 2 == 0){

	even_num_wd($encrypted_text);

}else{

	odd_num_wd($encrypted_text);

}



sub odd_num_wd{

@param = @_;

$cipher = "$param[0]";

@chars = split(//,$cipher);
$size = @chars;
$real_size = (($size * .5) + .5)-1;
$start2_size = (($size * .5) + .5);


foreach $w1(0..($size * .5) + .5){

	push(@wd1,$w1);


}

foreach $w2($start2_size..$size-1){

	push(@wd2,$w2);

}

foreach $f(0..(($size * .5) + .5)-1){

	$output = "$chars[$wd1[$f]]$chars[$wd2[$f]]";
	push (@out, $output);

}

$last_out = join("", @out);
$final_out = substr($last_out,0,$size);
print $final_out;

print "\n";

}


#############################################


sub even_num_wd{

@param = @_;

$cipher = "$param[0]";


@chars = split(//, $cipher);

$size = @chars;

foreach $w1(0..($size * .5) - 1){

	push(@wd1, $w1);

}

foreach $w2(($size * .5)..$size-1){

	push(@wd2, $w2);

}

foreach $f(0..($size * .5) - 1){

	$output = "$chars[$wd1[$f]]$chars[$wd2[$f]]";
	push (@out, $output);

}

$last_out = join("", @out);

print "$last_out\n";


}





























